{{- include "ffc-helm-library.azure-ingress-master" (list . "ffc-ffd-ingress.ingress") -}}
{{- define "ffc-ffd-ingress.ingress" -}}
metadata:
  annotations:
    nginx.ingress.kubernetes.io/app-root: {{ .Values.ingress.defaultPath }}
{{- end -}}
